project:
  type: site
  output-dir: docs

website:
  title: "Geotech at ASU"
  page-footer:
    center: 
      - text: "\\©2021-2022, ASU Geotech Group"
        href: about.qmd
  navbar:
    background: primary
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - organizations.qmd
      - news.qmd
      - about.qmd
      - icon: github
        href: https://github.com/geotechasu/soilrocks
format:
  html:
    theme: 
      - litera
      - ./assets/asu.scss
    css: assets/styles.css
    toc: true
