project:
  type: site
  output-dir: docs

website:
  title: "Geotech Group at ASU"
  page-footer:
    left: "Copyright 2021, ASU Geotech Group"
    right: 
      - text: "About"
        href: about.qmd
  navbar:
    background: primary
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - organizations.qmd
      - news.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/geotechasu/soilrocks
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - people.qmd
  #     - research.qmd
  #     - education.qmd
  #     - resources.qmd
  #     - organizations.qmd
  #     - news.qmd
  #     - about.qmd
format:
  html:
    theme: 
      - litera
      - ./assets/asu.scss
    highlight-style: github
    toc: true
