project:
  type: site
  output-dir: docs

website:
  title: "Geotech at ASU"
  favicon: ./img/favicon.png
  page-footer:
    center: 
      - text: "\\©2021-2022, ASU Geotech Group"
        href: about.qmd
  navbar:
    background: light
    foreground: black
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - organizations.qmd
      - news.qmd
      - about.qmd
      - icon: github
        href: https://github.com/geotechasu/soilrocks
format:
  html:
    theme: 
      - litera
      - ./assets/asu.scss
    css: assets/styles.css
    linkcolor: $red
    toc: true
    email-obfuscation: javascript
    include-in-header: 
      - assets/iconfonts.html
execute:
  echo: false
  warning: false 
  message: false
