project:
  type: site
  output-dir: docs

site:
  title: "Geotech Group at ASU"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - organizations.qmd
      - news.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/geotechasu/soilrocks
  sidebar:
    style: "docked"
    search: true
    contents:
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - organizations.qmd
      - news.qmd
      - about.qmd
format:
  html:
    theme: 
      # - litera
      - asu.scss
    margin-left: 10%
    max-width:  100%
    highlight-style: github
    toc: true
