---
title: "About"
---

Geotechnical and geoenvironmental engineering at ASU is focused upon unsaturated soil mechanics, biogetechnics, waste mechanics, and geotechnical earthquake engineering.

* ASU is a leader in unsaturated soil mechanics applied to the performance of pavement subgrades and the impact of expansive soil upon foundations.
ASU’s unsaturated soil mechanics laboratory is one of the finest in the world and has been responsible for many innovations in unsaturated soil testing.

* ASU is also a leader in the emerging field of biogeotechnics, including bio-mediated geotechnics and bio-inspired geotechnics. 
ASU is the headquarter of the Center for bio-mediated and bio-inspired Geotechnics (CBBG), a National Science Foundation Engineering Research Center since 2015. Three other partner universities include University of California, Davis, Georgia Institute of Technology, New Mexico State University. Under the leadership of ASU, the CBBG unites four partner Universities who are committed to a common goal of sustainable infrastructure development and rehabilitation and have strong ties to industrial partners and international collaborators. Visit [CBBG website](https://cbbg.engineering.asu.edu/) to learn more.

* ASU’s Enamul and Mahmuda Hoque laboratory has unique, large scale equipment for static and dynamic testing of waste materials. Research on the seismic design of geosynthetic lined landfills being conducted at ASU combines our strengths in waste properties and seismic analysis and design.

* The work of the Geotechnical and geoenvironmental engineering group at ASU on mitigation of geologic hazards (expansive soils, earthquake engineering) and environmental protection and remediation (landfill engineering) has many synergies with the School of Sustainable Engineering for the Built Environment and ASU’s emphasis on resilient and sustainable infrastructure. 

## Contact us

```{r}
#| echo: false
#| fig.height: 3
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=-111.93048, lat=33.42081, popup="Geo@ASU")
```
